### ISSUE TITLE
about page broken links

### ISSUE THREAD

**Issue by CaitSith2** [infinity-gbc/website#1]
Went ahead and checked through the website links,  to figure out which ones were broken, if any.

Seems "Justin Karneges",  "Hideaki Omuro", "Melvin de Voor" are all broken.  

For "Melvin de Voor", closest I could find was http://melvindevoor.deviantart.com/  (He seems to have a link in his deviant ID, but that is unfortunately defunct.)

Couldn't find a current web site for "Hideaki Omuro".

Finally, you probably should update yours, as you should know what it is.  :)

I am aware that Infinity is planned to be released soon,  through Matthew Velente's twitter.

**Comment by jkarneges** [comment]
Thanks for the report. This info is very old and we do need to update it.

**Comment by jkarneges** [comment]
Made some adjustments.
